// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	sqlc "banka-backend/services/user-service/internal/database/sqlc"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

// AssignUserPermission provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) AssignUserPermission(ctx context.Context, arg sqlc.AssignUserPermissionParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for AssignUserPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.AssignUserPermissionParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateEmployeeDetails provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateEmployeeDetails(ctx context.Context, arg sqlc.CreateEmployeeDetailsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmployeeDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateEmployeeDetailsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.CreateUserRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlc.CreateUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) (sqlc.CreateUserRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateUserParams) sqlc.CreateUserRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.CreateUserRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateVerificationToken provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateVerificationToken(ctx context.Context, arg sqlc.CreateVerificationTokenParams) (sqlc.CreateVerificationTokenRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 sqlc.CreateVerificationTokenRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateVerificationTokenParams) (sqlc.CreateVerificationTokenRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.CreateVerificationTokenParams) sqlc.CreateVerificationTokenRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sqlc.CreateVerificationTokenRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.CreateVerificationTokenParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserPermissions provides a mock function with given fields: ctx, userID
func (_m *MockQuerier) DeleteUserPermissions(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPermissions provides a mock function with given fields: ctx
func (_m *MockQuerier) GetAllPermissions(ctx context.Context) ([]sqlc.Permission, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPermissions")
	}

	var r0 []sqlc.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]sqlc.Permission, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []sqlc.Permission); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployeeByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetEmployeeByID(ctx context.Context, id int64) (sqlc.GetEmployeeByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEmployeeByID")
	}

	var r0 sqlc.GetEmployeeByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (sqlc.GetEmployeeByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) sqlc.GetEmployeeByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetEmployeeByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetUserByID(ctx context.Context, id int64) (sqlc.GetUserByIDRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 sqlc.GetUserByIDRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (sqlc.GetUserByIDRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) sqlc.GetUserByIDRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sqlc.GetUserByIDRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPermissions provides a mock function with given fields: ctx, userID
func (_m *MockQuerier) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVerificationToken provides a mock function with given fields: ctx, token
func (_m *MockQuerier) GetVerificationToken(ctx context.Context, token string) (sqlc.VerificationToken, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetVerificationToken")
	}

	var r0 sqlc.VerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sqlc.VerificationToken, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sqlc.VerificationToken); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(sqlc.VerificationToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListEmployees provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListEmployees(ctx context.Context, arg sqlc.ListEmployeesParams) ([]sqlc.ListEmployeesRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListEmployees")
	}

	var r0 []sqlc.ListEmployeesRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListEmployeesParams) ([]sqlc.ListEmployeesRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListEmployeesParams) []sqlc.ListEmployeesRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ListEmployeesRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListEmployeesParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkVerificationTokenUsed provides a mock function with given fields: ctx, id
func (_m *MockQuerier) MarkVerificationTokenUsed(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkVerificationTokenUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListClients provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) ListClients(ctx context.Context, arg sqlc.ListClientsParams) ([]sqlc.ListClientsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []sqlc.ListClientsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListClientsParams) ([]sqlc.ListClientsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.ListClientsParams) []sqlc.ListClientsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.ListClientsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.ListClientsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchClients provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SearchClients(ctx context.Context, arg sqlc.SearchClientsParams) ([]sqlc.SearchClientsRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchClients")
	}

	var r0 []sqlc.SearchClientsRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.SearchClientsParams) ([]sqlc.SearchClientsRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.SearchClientsParams) []sqlc.SearchClientsRow); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.SearchClientsRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sqlc.SearchClientsParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserPassword provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) SetUserPassword(ctx context.Context, arg sqlc.SetUserPasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.SetUserPasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEmployeeDetails provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateEmployeeDetails(ctx context.Context, arg sqlc.UpdateEmployeeDetailsParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEmployeeDetails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateEmployeeDetailsParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserActive provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUserActive(ctx context.Context, arg sqlc.UpdateUserActiveParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserActiveParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserPassword provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateUserPassword(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sqlc.UpdateUserPasswordParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
