// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	"context"

	domain "banka-backend/services/user-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

// GetClientByID provides a mock function with given fields: ctx, id
func (_m *MockClientService) GetClientByID(ctx context.Context, id int64) (*domain.ClientDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetClientByID")
	}

	var r0 *domain.ClientDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.ClientDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.ClientDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ClientDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListClients provides a mock function with given fields: ctx, filter
func (_m *MockClientService) ListClients(ctx context.Context, filter domain.ClientFilter) ([]domain.ClientSummary, bool, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []domain.ClientSummary
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ClientFilter) ([]domain.ClientSummary, bool, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ClientFilter) []domain.ClientSummary); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ClientSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ClientFilter) bool); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.ClientFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateClient provides a mock function with given fields: ctx, id, input
func (_m *MockClientService) UpdateClient(ctx context.Context, id int64, input domain.UpdateClientInput) (*domain.ClientDetail, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 *domain.ClientDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateClientInput) (*domain.ClientDetail, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.UpdateClientInput) *domain.ClientDetail); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ClientDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.UpdateClientInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
