// Code generated by mockery. DO NOT EDIT.
// Re-generate with: mockery --config .mockery.yaml
package mocks

import (
	"context"
	"database/sql"
	"time"

	sqlc "banka-backend/services/user-service/internal/database/sqlc"

	"github.com/stretchr/testify/mock"
)

// MockQuerier is a testify/mock implementation of sqlc.Querier.
type MockQuerier struct {
	mock.Mock
}

func (m *MockQuerier) AssignUserPermission(ctx context.Context, arg sqlc.AssignUserPermissionParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) CreateEmployeeDetails(ctx context.Context, arg sqlc.CreateEmployeeDetailsParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.CreateUserRow, error) {
	args := m.Called(ctx, arg)
	if args.Get(0) == nil {
		return sqlc.CreateUserRow{}, args.Error(1)
	}
	return args.Get(0).(sqlc.CreateUserRow), args.Error(1)
}

func (m *MockQuerier) CreateVerificationToken(ctx context.Context, arg sqlc.CreateVerificationTokenParams) (sqlc.CreateVerificationTokenRow, error) {
	args := m.Called(ctx, arg)
	if args.Get(0) == nil {
		return sqlc.CreateVerificationTokenRow{}, args.Error(1)
	}
	return args.Get(0).(sqlc.CreateVerificationTokenRow), args.Error(1)
}

func (m *MockQuerier) DeleteUserPermissions(ctx context.Context, userID int64) error {
	args := m.Called(ctx, userID)
	return args.Error(0)
}

func (m *MockQuerier) GetAllPermissions(ctx context.Context) ([]sqlc.Permission, error) {
	args := m.Called(ctx)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]sqlc.Permission), args.Error(1)
}

func (m *MockQuerier) GetEmployeeByID(ctx context.Context, id int64) (sqlc.GetEmployeeByIDRow, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return sqlc.GetEmployeeByIDRow{}, args.Error(1)
	}
	return args.Get(0).(sqlc.GetEmployeeByIDRow), args.Error(1)
}

func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	args := m.Called(ctx, email)
	if args.Get(0) == nil {
		return sqlc.User{}, args.Error(1)
	}
	return args.Get(0).(sqlc.User), args.Error(1)
}

func (m *MockQuerier) GetUserByID(ctx context.Context, id int64) (sqlc.GetUserByIDRow, error) {
	args := m.Called(ctx, id)
	if args.Get(0) == nil {
		return sqlc.GetUserByIDRow{}, args.Error(1)
	}
	return args.Get(0).(sqlc.GetUserByIDRow), args.Error(1)
}

func (m *MockQuerier) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	args := m.Called(ctx, userID)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]string), args.Error(1)
}

func (m *MockQuerier) GetVerificationToken(ctx context.Context, token string) (sqlc.VerificationToken, error) {
	args := m.Called(ctx, token)
	if args.Get(0) == nil {
		return sqlc.VerificationToken{}, args.Error(1)
	}
	return args.Get(0).(sqlc.VerificationToken), args.Error(1)
}

func (m *MockQuerier) ListEmployees(ctx context.Context, arg sqlc.ListEmployeesParams) ([]sqlc.ListEmployeesRow, error) {
	args := m.Called(ctx, arg)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]sqlc.ListEmployeesRow), args.Error(1)
}

func (m *MockQuerier) MarkVerificationTokenUsed(ctx context.Context, id int64) error {
	args := m.Called(ctx, id)
	return args.Error(0)
}

func (m *MockQuerier) SetUserPassword(ctx context.Context, arg sqlc.SetUserPasswordParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) UpdateEmployeeDetails(ctx context.Context, arg sqlc.UpdateEmployeeDetailsParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) UpdateUserActive(ctx context.Context, arg sqlc.UpdateUserActiveParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) UpdateUserPassword(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error {
	args := m.Called(ctx, arg)
	return args.Error(0)
}

func (m *MockQuerier) SearchClients(ctx context.Context, arg sqlc.SearchClientsParams) ([]sqlc.SearchClientsRow, error) {
	args := m.Called(ctx, arg)
	return args.Get(0).([]sqlc.SearchClientsRow), args.Error(1)
}

// Ensure MockQuerier implements sqlc.Querier at compile time.
var _ sqlc.Querier = (*MockQuerier)(nil)

// Unused import guard — time is needed for VerificationToken fields in tests.
var _ = time.Now
var _ = sql.NullString{}
