// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// ─── Permissions (required for CreateEmployee and Login JWT) ──────────────────
	// Links a permission to an employee via the user_permissions junction table.
	// Call once per permission code when creating an employee (Issue 9).
	AssignUserPermission(ctx context.Context, arg AssignUserPermissionParams) error
	// Inserts the employee-specific extension row in employee_details.
	// Must be called after CreateUser within the same transaction.
	CreateEmployeeDetails(ctx context.Context, arg CreateEmployeeDetailsParams) error
	// =============================================================================
	// sqlc queries for the user-service
	// Run `sqlc generate` from services/user-service/ to regenerate Go code.
	//
	// Naming convention:
	//   :one   → returns a single row  (sql.ErrNoRows if not found)
	//   :exec  → returns no rows       (only checks for execution error)
	//   :many  → returns []Row
	// =============================================================================
	// ─── User creation ────────────────────────────────────────────────────────────
	// Inserts a new base user row. password_hash and salt_password start empty;
	// they are populated when the employee activates their account (Issue 11).
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ─── Account activation / password reset (Issues 10, 11, 12) ─────────────────
	// Stores a new single-use token for account activation or password reset.
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (CreateVerificationTokenRow, error)
	// Removes all permission assignments for a user.
	// Called before re-assigning the full permission set in UpdateEmployee.
	DeleteUserPermissions(ctx context.Context, userID int64) error
	// ─── Permission codebook (Issue 5) ───────────────────────────────────────────
	// Returns the complete permission codebook, ordered by id.
	// Used by the admin frontend to populate Create/Edit Employee permission lists.
	GetAllPermissions(ctx context.Context) ([]Permission, error)
	// ─── Employee detail lookup (Issue 7) ────────────────────────────────────────
	// Full employee profile for the edit form: users JOIN employee_details.
	// Returns sql.ErrNoRows when the user does not exist or has no employee_details row.
	GetEmployeeByID(ctx context.Context, id int64) (GetEmployeeByIDRow, error)
	// ─── Authentication ───────────────────────────────────────────────────────────
	// Full row including password_hash and salt_password.
	// ONLY used by the Login handler to verify credentials — never returned to the caller.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// ─── Profile lookup ───────────────────────────────────────────────────────────
	// Safe projection — excludes password_hash and salt_password.
	// Used by GetEmployee, token refresh, and internal service calls.
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// Returns all permission codes held by a user.
	// Used during Login to populate the `permissions` claim in the JWT (Issue 4).
	GetUserPermissions(ctx context.Context, userID int64) ([]string, error)
	// Fetches a token row for validation. The caller must check:
	//   - used_at IS NULL     (not yet consumed)
	//   - expires_at > NOW()  (not expired)
	GetVerificationToken(ctx context.Context, token string) (VerificationToken, error)
	// ─── Employee listing (Issue 6) ───────────────────────────────────────────────
	// Returns employees matching the optional filters, with pagination.
	// Pass NULL for any filter to skip it; the handler maps "" → nil for that purpose.
	// Joins employee_details so only users with an employee profile are returned.
	ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error)
	// ─── Client search (Autocomplete / Infinite Scroll) ───────────────────────────
	// Returns clients matching an optional query string against first_name, last_name,
	// or email, ordered by created_at DESC. Pass NULL for query to return all clients.
	// Request limit+1 rows from the caller to support has_more detection.
	SearchClients(ctx context.Context, arg SearchClientsParams) ([]SearchClientsRow, error)
	// Marks the token as consumed so it cannot be replayed (Issue 11 edge case).
	MarkVerificationTokenUsed(ctx context.Context, id int64) error
	// ─── Password update ──────────────────────────────────────────────────────────
	// Writes the hashed password and salt after successful activation or reset.
	// Only called from the ActivateAccount and SetNewPassword handlers.
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// Updates position and department for an existing employee_details row.
	UpdateEmployeeDetails(ctx context.Context, arg UpdateEmployeeDetailsParams) error
	// ─── Employee update (Issue 8) ───────────────────────────────────────────────
	// Updates the mutable base fields of an existing user row.
	// Called inside a transaction by UpdateEmployee; never updates password_hash/salt.
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	// ─── Account activation / set password (Issue 11) ───────────────────────────
	// Sets the password hash for the user identified by email.
	// Called by SetPassword after the activation token is verified.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
