// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const assignUserPermission = `-- name: AssignUserPermission :exec

INSERT INTO user_permissions (user_id, permission_id)
SELECT $1, id
FROM permissions
WHERE permission_code = $2
ON CONFLICT DO NOTHING
`

type AssignUserPermissionParams struct {
	UserID         int64  `json:"user_id"`
	PermissionCode string `json:"permission_code"`
}

// ─── Permissions (required for CreateEmployee and Login JWT) ──────────────────
// Links a permission to an employee via the user_permissions junction table.
// Call once per permission code when creating an employee (Issue 9).
func (q *Queries) AssignUserPermission(ctx context.Context, arg AssignUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, assignUserPermission, arg.UserID, arg.PermissionCode)
	return err
}

const createEmployeeDetails = `-- name: CreateEmployeeDetails :exec
INSERT INTO employee_details (user_id, username, position, department)
VALUES ($1, $2, $3, $4)
`

type CreateEmployeeDetailsParams struct {
	UserID     int64          `json:"user_id"`
	Username   string         `json:"username"`
	Position   sql.NullString `json:"position"`
	Department sql.NullString `json:"department"`
}

// Inserts the employee-specific extension row in employee_details.
// Must be called after CreateUser within the same transaction.
func (q *Queries) CreateEmployeeDetails(ctx context.Context, arg CreateEmployeeDetailsParams) error {
	_, err := q.db.ExecContext(ctx, createEmployeeDetails,
		arg.UserID,
		arg.Username,
		arg.Position,
		arg.Department,
	)
	return err
}

const createUser = `-- name: CreateUser :one


INSERT INTO users (
    email,
    password_hash,
    salt_password,
    user_type,
    first_name,
    last_name,
    birth_date,
    gender,
    phone_number,
    address,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, email, user_type, first_name, last_name, is_active, created_at
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	SaltPassword string         `json:"salt_password"`
	UserType     string         `json:"user_type"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	BirthDate    int64          `json:"birth_date"`
	Gender       sql.NullString `json:"gender"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	Address      sql.NullString `json:"address"`
	IsActive     bool           `json:"is_active"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	UserType  string    `json:"user_type"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

// =============================================================================
// sqlc queries for the user-service
// Run `sqlc generate` from services/user-service/ to regenerate Go code.
//
// Naming convention:
//
//	:one   → returns a single row  (sql.ErrNoRows if not found)
//	:exec  → returns no rows       (only checks for execution error)
//	:many  → returns []Row
//
// =============================================================================
// ─── User creation ────────────────────────────────────────────────────────────
// Inserts a new base user row. password_hash and salt_password start empty;
// they are populated when the employee activates their account (Issue 11).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.SaltPassword,
		arg.UserType,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.PhoneNumber,
		arg.Address,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserType,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one

INSERT INTO verification_tokens (user_id, token, token_type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token, expires_at
`

type CreateVerificationTokenParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	TokenType string    `json:"token_type"`
	ExpiresAt time.Time `json:"expires_at"`
}

type CreateVerificationTokenRow struct {
	ID        int64     `json:"id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

// ─── Account activation / password reset (Issues 10, 11, 12) ─────────────────
// Stores a new single-use token for account activation or password reset.
func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (CreateVerificationTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createVerificationToken,
		arg.UserID,
		arg.Token,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i CreateVerificationTokenRow
	err := row.Scan(&i.ID, &i.Token, &i.ExpiresAt)
	return i, err
}

const deleteUserPermissions = `-- name: DeleteUserPermissions :exec
DELETE FROM user_permissions WHERE user_id = $1
`

// Removes all permission assignments for a user.
// Called before re-assigning the full permission set in UpdateEmployee.
func (q *Queries) DeleteUserPermissions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserPermissions, userID)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many

SELECT id, permission_code FROM permissions ORDER BY id ASC
`

// ─── Permission codebook (Issue 5) ───────────────────────────────────────────
// Returns the complete permission codebook, ordered by id.
// Used by the admin frontend to populate Create/Edit Employee permission lists.
func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeByID = `-- name: GetEmployeeByID :one

SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    u.birth_date,
    u.gender,
    u.phone_number,
    u.address,
    u.user_type,
    u.is_active,
    u.created_at,
    e.username,
    e.position,
    e.department
FROM users u
INNER JOIN employee_details e ON e.user_id = u.id
WHERE u.id = $1
LIMIT 1
`

type GetEmployeeByIDRow struct {
	ID          int64          `json:"id"`
	Email       string         `json:"email"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	BirthDate   int64          `json:"birth_date"`
	Gender      sql.NullString `json:"gender"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Address     sql.NullString `json:"address"`
	UserType    string         `json:"user_type"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
	Username    string         `json:"username"`
	Position    sql.NullString `json:"position"`
	Department  sql.NullString `json:"department"`
}

// ─── Employee detail lookup (Issue 7) ────────────────────────────────────────
// Full employee profile for the edit form: users JOIN employee_details.
// Returns sql.ErrNoRows when the user does not exist or has no employee_details row.
func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.PhoneNumber,
		&i.Address,
		&i.UserType,
		&i.IsActive,
		&i.CreatedAt,
		&i.Username,
		&i.Position,
		&i.Department,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT
    id,
    email,
    password_hash,
    salt_password,
    user_type,
    first_name,
    last_name,
    birth_date,
    gender,
    phone_number,
    address,
    is_active,
    created_at
FROM users
WHERE email = $1
LIMIT 1
`

// ─── Authentication ───────────────────────────────────────────────────────────
// Full row including password_hash and salt_password.
// ONLY used by the Login handler to verify credentials — never returned to the caller.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.SaltPassword,
		&i.UserType,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.PhoneNumber,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT
    id,
    email,
    user_type,
    first_name,
    last_name,
    birth_date,
    gender,
    phone_number,
    address,
    is_active,
    created_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID          int64          `json:"id"`
	Email       string         `json:"email"`
	UserType    string         `json:"user_type"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	BirthDate   int64          `json:"birth_date"`
	Gender      sql.NullString `json:"gender"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Address     sql.NullString `json:"address"`
	IsActive    bool           `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
}

// ─── Profile lookup ───────────────────────────────────────────────────────────
// Safe projection — excludes password_hash and salt_password.
// Used by GetEmployee, token refresh, and internal service calls.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserType,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Gender,
		&i.PhoneNumber,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.permission_code
FROM permissions p
INNER JOIN user_permissions up ON up.permission_id = p.id
WHERE up.user_id = $1
ORDER BY p.permission_code
`

// Returns all permission codes held by a user.
// Used during Login to populate the `permissions` claim in the JWT (Issue 4).
func (q *Queries) GetUserPermissions(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_code string
		if err := rows.Scan(&permission_code); err != nil {
			return nil, err
		}
		items = append(items, permission_code)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT id, user_id, token, token_type, expires_at, used_at
FROM verification_tokens
WHERE token = $1
LIMIT 1
`

// Fetches a token row for validation. The caller must check:
//   - used_at IS NULL     (not yet consumed)
//   - expires_at > NOW()  (not expired)
func (q *Queries) GetVerificationToken(ctx context.Context, token string) (VerificationToken, error) {
	row := q.db.QueryRowContext(ctx, getVerificationToken, token)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.TokenType,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many

SELECT
    u.id,
    u.email,
    u.first_name,
    u.last_name,
    u.user_type,
    u.is_active,
    u.phone_number,
    e.position,
    e.department
FROM users u
INNER JOIN employee_details e ON e.user_id = u.id
WHERE
    ($3::text      IS NULL OR u.email      ILIKE '%' || $3::text      || '%')
AND ($4::text IS NULL OR u.first_name ILIKE '%' || $4::text || '%')
AND ($5::text  IS NULL OR u.last_name  ILIKE '%' || $5::text  || '%')
AND ($6::text   IS NULL OR e.position   ILIKE '%' || $6::text   || '%')
ORDER BY u.id ASC
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit     int32          `json:"limit"`
	Offset    int32          `json:"offset"`
	Email     sql.NullString `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Position  sql.NullString `json:"position"`
}

type ListEmployeesRow struct {
	ID          int64          `json:"id"`
	Email       string         `json:"email"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	UserType    string         `json:"user_type"`
	IsActive    bool           `json:"is_active"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Position    sql.NullString `json:"position"`
	Department  sql.NullString `json:"department"`
}

// ─── Employee listing (Issue 6) ───────────────────────────────────────────────
// Returns employees matching the optional filters, with pagination.
// Pass NULL for any filter to skip it; the handler maps "" → nil for that purpose.
// Joins employee_details so only users with an employee profile are returned.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees,
		arg.Limit,
		arg.Offset,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Position,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.UserType,
			&i.IsActive,
			&i.PhoneNumber,
			&i.Position,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT
    u.id,
    u.first_name,
    u.last_name,
    u.email
FROM users u
WHERE u.user_type = 'CLIENT'
AND ($3::text IS NULL
     OR u.first_name ILIKE '%' || $3::text || '%'
     OR u.last_name  ILIKE '%' || $3::text || '%'
     OR u.email      ILIKE '%' || $3::text || '%')
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type SearchClientsParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Query  sql.NullString `json:"query"`
}

type SearchClientsRow struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}

// ─── Client search (Autocomplete / Infinite Scroll) ───────────────────────────
// Returns clients matching an optional query string with pagination.
// Pass NULL for query to return all clients.
func (q *Queries) SearchClients(ctx context.Context, arg SearchClientsParams) ([]SearchClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchClients,
		arg.Limit,
		arg.Offset,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClientsRow{}
	for rows.Next() {
		var i SearchClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT
    u.id,
    u.first_name,
    u.last_name,
    u.email,
    u.phone_number
FROM users u
WHERE u.user_type = 'CLIENT'
  AND (
    $3::text IS NULL
    OR u.first_name ILIKE '%' || $3::text || '%'
    OR u.last_name  ILIKE '%' || $3::text || '%'
    OR (u.first_name || ' ' || u.last_name) ILIKE '%' || $3::text || '%'
  )
  AND ($4::text IS NULL OR u.email ILIKE '%' || $4::text || '%')
ORDER BY u.last_name ASC, u.first_name ASC
LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Name   sql.NullString `json:"name"`  // partial match on first_name, last_name, or "first last"
	Email  sql.NullString `json:"email"` // partial match on email
}

type ListClientsRow struct {
	ID          int64          `json:"id"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
}

// ListClients returns clients matching optional name/email filters, sorted
// alphabetically by last name.  Pass NULL for either filter to skip it.
// Request limit+1 rows from the caller to support has_more detection.
func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]ListClientsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClients,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Email,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientsRow{}
	for rows.Next() {
		var i ListClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE verification_tokens
SET used_at = NOW()
WHERE id = $1
`

// Marks the token as consumed so it cannot be replayed (Issue 11 edge case).
func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markVerificationTokenUsed, id)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec

UPDATE users
SET password_hash = $2,
    salt_password = $3,
    is_active     = TRUE
WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
	SaltPassword string `json:"salt_password"`
}

// ─── Password update ──────────────────────────────────────────────────────────
// Writes the hashed password and salt after successful activation or reset.
// Only called from the ActivateAccount and SetNewPassword handlers.
func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, setUserPassword, arg.ID, arg.PasswordHash, arg.SaltPassword)
	return err
}

const updateEmployeeDetails = `-- name: UpdateEmployeeDetails :exec
UPDATE employee_details
SET position   = $2,
    department = $3
WHERE user_id = $1
`

type UpdateEmployeeDetailsParams struct {
	UserID     int64          `json:"user_id"`
	Position   sql.NullString `json:"position"`
	Department sql.NullString `json:"department"`
}

// Updates position and department for an existing employee_details row.
func (q *Queries) UpdateEmployeeDetails(ctx context.Context, arg UpdateEmployeeDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeDetails, arg.UserID, arg.Position, arg.Department)
	return err
}

const updateUser = `-- name: UpdateUser :exec

UPDATE users
SET email        = $2,
    first_name   = $3,
    last_name    = $4,
    birth_date   = $5,
    gender       = $6,
    phone_number = $7,
    address      = $8,
    is_active    = $9
WHERE id = $1
`

type UpdateUserParams struct {
	ID          int64          `json:"id"`
	Email       string         `json:"email"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	BirthDate   int64          `json:"birth_date"`
	Gender      sql.NullString `json:"gender"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Address     sql.NullString `json:"address"`
	IsActive    bool           `json:"is_active"`
}

// ─── Employee update (Issue 8) ───────────────────────────────────────────────
// Updates the mutable base fields of an existing user row.
// Called inside a transaction by UpdateEmployee; never updates password_hash/salt.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Gender,
		arg.PhoneNumber,
		arg.Address,
		arg.IsActive,
	)
	return err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, arg.ID, arg.IsActive)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec

UPDATE users SET password_hash = $1 WHERE email = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
}

// ─── Account activation / set password (Issue 11) ───────────────────────────
// Sets the password hash for the user identified by email.
// Called by SetPassword after the activation token is verified.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.Email)
	return err
}
