// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.0
// source: proto/banka/banka.proto

package bankav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankaService_GetCurrencies_FullMethodName            = "/banka.v1.BankaService/GetCurrencies"
	BankaService_GetDelatnosti_FullMethodName            = "/banka.v1.BankaService/GetDelatnosti"
	BankaService_CreateAccount_FullMethodName            = "/banka.v1.BankaService/CreateAccount"
	BankaService_GetClientAccounts_FullMethodName        = "/banka.v1.BankaService/GetClientAccounts"
	BankaService_GetAccountDetail_FullMethodName         = "/banka.v1.BankaService/GetAccountDetail"
	BankaService_GetAccountTransactions_FullMethodName   = "/banka.v1.BankaService/GetAccountTransactions"
	BankaService_RenameAccount_FullMethodName            = "/banka.v1.BankaService/RenameAccount"
	BankaService_UpdateAccountLimit_FullMethodName       = "/banka.v1.BankaService/UpdateAccountLimit"
	BankaService_GetPendingAction_FullMethodName         = "/banka.v1.BankaService/GetPendingAction"
	BankaService_GetPendingActions_FullMethodName        = "/banka.v1.BankaService/GetPendingActions"
	BankaService_ApprovePendingAction_FullMethodName     = "/banka.v1.BankaService/ApprovePendingAction"
	BankaService_VerifyLimitChange_FullMethodName        = "/banka.v1.BankaService/VerifyLimitChange"
	BankaService_GetPaymentRecipients_FullMethodName     = "/banka.v1.BankaService/GetPaymentRecipients"
	BankaService_CreatePaymentRecipient_FullMethodName   = "/banka.v1.BankaService/CreatePaymentRecipient"
	BankaService_UpdatePaymentRecipient_FullMethodName   = "/banka.v1.BankaService/UpdatePaymentRecipient"
	BankaService_DeletePaymentRecipient_FullMethodName   = "/banka.v1.BankaService/DeletePaymentRecipient"
	BankaService_CreatePaymentIntent_FullMethodName      = "/banka.v1.BankaService/CreatePaymentIntent"
	BankaService_CreateTransferIntent_FullMethodName     = "/banka.v1.BankaService/CreateTransferIntent"
	BankaService_VerifyAndExecutePayment_FullMethodName  = "/banka.v1.BankaService/VerifyAndExecutePayment"
	BankaService_GetPaymentHistory_FullMethodName        = "/banka.v1.BankaService/GetPaymentHistory"
	BankaService_GetPaymentDetail_FullMethodName         = "/banka.v1.BankaService/GetPaymentDetail"
	BankaService_ApplyForCredit_FullMethodName           = "/banka.v1.BankaService/ApplyForCredit"
	BankaService_GetClientCredits_FullMethodName         = "/banka.v1.BankaService/GetClientCredits"
	BankaService_GetCreditDetails_FullMethodName         = "/banka.v1.BankaService/GetCreditDetails"
	BankaService_GetAllCreditRequests_FullMethodName     = "/banka.v1.BankaService/GetAllCreditRequests"
	BankaService_ApproveCredit_FullMethodName            = "/banka.v1.BankaService/ApproveCredit"
	BankaService_RejectCredit_FullMethodName             = "/banka.v1.BankaService/RejectCredit"
	BankaService_GetAllApprovedCredits_FullMethodName    = "/banka.v1.BankaService/GetAllApprovedCredits"
	BankaService_EmployeeChangeCardStatus_FullMethodName = "/banka.v1.BankaService/EmployeeChangeCardStatus"
	BankaService_GetAllAccounts_FullMethodName           = "/banka.v1.BankaService/GetAllAccounts"
	BankaService_GetAccountCards_FullMethodName          = "/banka.v1.BankaService/GetAccountCards"
	BankaService_ListExchanges_FullMethodName            = "/banka.v1.BankaService/ListExchanges"
	BankaService_GetExchange_FullMethodName              = "/banka.v1.BankaService/GetExchange"
	BankaService_ToggleMarketTestMode_FullMethodName     = "/banka.v1.BankaService/ToggleMarketTestMode"
	BankaService_GetListings_FullMethodName              = "/banka.v1.BankaService/GetListings"
	BankaService_GetListingByID_FullMethodName           = "/banka.v1.BankaService/GetListingByID"
	BankaService_GetListingHistory_FullMethodName        = "/banka.v1.BankaService/GetListingHistory"
	BankaService_CreateListingOrder_FullMethodName       = "/banka.v1.BankaService/CreateListingOrder"
	BankaService_TradingCalculate_FullMethodName         = "/banka.v1.BankaService/TradingCalculate"
	BankaService_TradingCreateOrder_FullMethodName       = "/banka.v1.BankaService/TradingCreateOrder"
	BankaService_TradingListOrders_FullMethodName        = "/banka.v1.BankaService/TradingListOrders"
	BankaService_TradingApproveOrder_FullMethodName      = "/banka.v1.BankaService/TradingApproveOrder"
	BankaService_TradingDeclineOrder_FullMethodName      = "/banka.v1.BankaService/TradingDeclineOrder"
	BankaService_TradingCancelOrder_FullMethodName       = "/banka.v1.BankaService/TradingCancelOrder"
)

// BankaServiceClient is the client API for BankaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankaServiceClient interface {
	// GetCurrencies — javna metoda, vraća sve podržane valute.
	GetCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCurrenciesResponse, error)
	// GetDelatnosti — javna metoda, vraća šifarnik delatnosti.
	GetDelatnosti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDelatnostiResponse, error)
	// CreateAccount — Employee only. Kreira novi bankovni račun.
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// GetClientAccounts — Client only. Vraća aktivne račune trenutno prijavljenog klijenta.
	GetClientAccounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientAccountsResponse, error)
	// GetAccountDetail — Client only. Vraća detalje jednog računa.
	GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*AccountDetail, error)
	// GetAccountTransactions — Client only. Vraća transakcije za dati račun.
	GetAccountTransactions(ctx context.Context, in *GetAccountTransactionsRequest, opts ...grpc.CallOption) (*GetAccountTransactionsResponse, error)
	// RenameAccount — Client only. Menja naziv računa.
	RenameAccount(ctx context.Context, in *RenameAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// UpdateAccountLimit — Client only. Kreira pending action za promenu limita.
	UpdateAccountLimit(ctx context.Context, in *UpdateAccountLimitRequest, opts ...grpc.CallOption) (*UpdateAccountLimitResponse, error)
	// GetPendingAction — Client only. Vraća jednu pending akciju.
	GetPendingAction(ctx context.Context, in *GetPendingActionRequest, opts ...grpc.CallOption) (*GetPendingActionResponse, error)
	// GetPendingActions — Client only. Vraća pending akcije za mobilni.
	// MORA biti registrovana POSLE GetPendingAction jer grpc-gateway v2 prepend-uje handlere
	// (poslje registrovani imaju prioritet). Statička ruta /pending mora pobediti {id}.
	GetPendingActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPendingActionsResponse, error)
	// ApprovePendingAction — Client only. Odobrava akciju i generiše verifikacioni kod.
	ApprovePendingAction(ctx context.Context, in *ApprovePendingActionRequest, opts ...grpc.CallOption) (*ApprovePendingActionResponse, error)
	// VerifyLimitChange — Client only. Proverava kod i primenjuje promenu limita.
	VerifyLimitChange(ctx context.Context, in *VerifyLimitChangeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetPaymentRecipients — Client only. Lista sačuvanih primalaca.
	GetPaymentRecipients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPaymentRecipientsResponse, error)
	// CreatePaymentRecipient — Client only. Dodaje novog primaoca.
	CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientItem, error)
	// UpdatePaymentRecipient — Client only. Menja primaoca.
	UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientItem, error)
	// DeletePaymentRecipient — Client only. Briše primaoca.
	DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CreatePaymentIntent — Client only. Kreira nalog plaćanja i pokreće verifikaciju.
	CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error)
	// CreateTransferIntent — Client only. Kreira nalog prenosa između računa istog klijenta.
	CreateTransferIntent(ctx context.Context, in *CreateTransferIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error)
	// VerifyAndExecutePayment — Client only. Proverava verifikacioni kod i izvršava plaćanje.
	VerifyAndExecutePayment(ctx context.Context, in *VerifyPaymentRequest, opts ...grpc.CallOption) (*PaymentIntentItem, error)
	// GetPaymentHistory — Client only. Istorija plaćanja sa filterima.
	GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error)
	// GetPaymentDetail — Client only. Detalji jednog naloga.
	GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*PaymentIntentItem, error)
	// ApplyForCredit — Client only. Podnosi zahtev za novi kredit.
	ApplyForCredit(ctx context.Context, in *ApplyForCreditRequest, opts ...grpc.CallOption) (*ApplyForCreditResponse, error)
	// GetClientCredits — Client only. Vraća sve kredite prijavljenog klijenta, sortirano opadajuće po iznosu.
	GetClientCredits(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientCreditsResponse, error)
	// GetCreditDetails — Client only. Vraća detalje i rate za jedan kredit.
	GetCreditDetails(ctx context.Context, in *GetCreditDetailsRequest, opts ...grpc.CallOption) (*GetCreditDetailsResponse, error)
	// GetAllCreditRequests — Employee only. Vraća sve zahteve za kredit sa opcionim filterima.
	GetAllCreditRequests(ctx context.Context, in *GetAllCreditRequestsRequest, opts ...grpc.CallOption) (*GetAllCreditRequestsResponse, error)
	// ApproveCredit — Employee only. Odobrava zahtev za kredit i uplaćuje iznos na račun klijenta.
	ApproveCredit(ctx context.Context, in *ApproveCreditRequest, opts ...grpc.CallOption) (*ApproveCreditResponse, error)
	// RejectCredit — Employee only. Odbija zahtev za kredit.
	RejectCredit(ctx context.Context, in *RejectCreditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetAllApprovedCredits — Employee only. Vraća sve odobrene kredite sa opcionim filterima, sortirano po broju računa.
	GetAllApprovedCredits(ctx context.Context, in *GetAllApprovedCreditsRequest, opts ...grpc.CallOption) (*GetAllApprovedCreditsResponse, error)
	// EmployeeChangeCardStatus — Employee only. Menja status kartice (blokada/deblokada/deaktivacija).
	// Nakon uspešne promene šalje asinhronu email notifikaciju vlasniku, a za poslovne račune
	// i ovlašćenom licu (email se čita iz lokalne baze, bez dodatnog poziva ka user-service-u).
	EmployeeChangeCardStatus(ctx context.Context, in *EmployeeChangeCardStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetAllAccounts — Employee only. Vraća agregiranu listu svih računa klijenata,
	// sortiranu abecedno po prezimenu vlasnika. Podržava filtere po broju računa,
	// imenu i prezimenu vlasnika (prosleđuju se kao query parametri).
	GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (*GetAllAccountsResponse, error)
	// GetAccountCards — Employee only. Vraća sve kartice vezane za dati račun.
	// Ime, prezime i email vlasnika dohvataju se sinhronim pozivom ka user-service-u.
	GetAccountCards(ctx context.Context, in *GetAccountCardsRequest, opts ...grpc.CallOption) (*GetAccountCardsResponse, error)
	// ListExchanges — javna metoda. Vraća listu berzi sa opcionim filterima.
	// Filteri: polity (tačno poklapanje), search (parcijalni match na name/acronym).
	ListExchanges(ctx context.Context, in *ListExchangesRequest, opts ...grpc.CallOption) (*ListExchangesResponse, error)
	// GetExchange — javna metoda. Dohvata jednu berzu po ID-u ili MIC kodu.
	// Prosleđuje se ili id (path param) ili mic_code (query param) — ne oba.
	GetExchange(ctx context.Context, in *GetExchangeRequest, opts ...grpc.CallOption) (*Exchange, error)
	// ToggleMarketTestMode — Admin/Employee only. Uključuje ili isključuje
	// bypass radnog vremena berzi (čuva se u Redisu pod ključem market:test_mode).
	ToggleMarketTestMode(ctx context.Context, in *ToggleMarketTestModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetListings — Client only. Vraća listu hartija sa filterima i paginacijom.
	GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error)
	// GetListingByID — Client only. Vraća detalje jedne hartije po ID-u.
	GetListingByID(ctx context.Context, in *GetListingByIDRequest, opts ...grpc.CallOption) (*ListingDetail, error)
	// GetListingHistory — Client only. Vraća istoriju dnevnih cena za datu hartiju.
	GetListingHistory(ctx context.Context, in *GetListingHistoryRequest, opts ...grpc.CallOption) (*GetListingHistoryResponse, error)
	// CreateListingOrder — Client only. Provera raspoloživog stanja; ne knjiži trgovinu (Celina 4).
	CreateListingOrder(ctx context.Context, in *CreateListingOrderRequest, opts ...grpc.CallOption) (*CreateListingOrderResponse, error)
	// TradingCalculate — Authenticated. Vraća procenu cene i provizije bez perzistencije.
	TradingCalculate(ctx context.Context, in *TradingCalculateRequest, opts ...grpc.CallOption) (*TradingCalculateResponse, error)
	// TradingCreateOrder — Authenticated. Kreira novi nalog; workflow odobravanja je u servisu.
	TradingCreateOrder(ctx context.Context, in *TradingCreateOrderRequest, opts ...grpc.CallOption) (*TradingCreateOrderResponse, error)
	// TradingListOrders — Employee only. Lista naloga sa opcionim filterom statusa.
	TradingListOrders(ctx context.Context, in *TradingListOrdersRequest, opts ...grpc.CallOption) (*TradingListOrdersResponse, error)
	// TradingApproveOrder — Employee only. Odobrava PENDING nalog.
	TradingApproveOrder(ctx context.Context, in *TradingApproveOrderRequest, opts ...grpc.CallOption) (*TradingApproveOrderResponse, error)
	// TradingDeclineOrder — Employee only. Odbija PENDING nalog.
	TradingDeclineOrder(ctx context.Context, in *TradingDeclineOrderRequest, opts ...grpc.CallOption) (*TradingDeclineOrderResponse, error)
	// TradingCancelOrder — Vlasnik naloga ili Employee. Otkazuje aktivan nalog.
	TradingCancelOrder(ctx context.Context, in *TradingCancelOrderRequest, opts ...grpc.CallOption) (*TradingCancelOrderResponse, error)
}

type bankaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankaServiceClient(cc grpc.ClientConnInterface) BankaServiceClient {
	return &bankaServiceClient{cc}
}

func (c *bankaServiceClient) GetCurrencies(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrenciesResponse)
	err := c.cc.Invoke(ctx, BankaService_GetCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetDelatnosti(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetDelatnostiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDelatnostiResponse)
	err := c.cc.Invoke(ctx, BankaService_GetDelatnosti_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, BankaService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetClientAccounts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientAccountsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetClientAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAccountDetail(ctx context.Context, in *GetAccountDetailRequest, opts ...grpc.CallOption) (*AccountDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountDetail)
	err := c.cc.Invoke(ctx, BankaService_GetAccountDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAccountTransactions(ctx context.Context, in *GetAccountTransactionsRequest, opts ...grpc.CallOption) (*GetAccountTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountTransactionsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetAccountTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) RenameAccount(ctx context.Context, in *RenameAccountRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_RenameAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) UpdateAccountLimit(ctx context.Context, in *UpdateAccountLimitRequest, opts ...grpc.CallOption) (*UpdateAccountLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccountLimitResponse)
	err := c.cc.Invoke(ctx, BankaService_UpdateAccountLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetPendingAction(ctx context.Context, in *GetPendingActionRequest, opts ...grpc.CallOption) (*GetPendingActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingActionResponse)
	err := c.cc.Invoke(ctx, BankaService_GetPendingAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetPendingActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPendingActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingActionsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetPendingActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) ApprovePendingAction(ctx context.Context, in *ApprovePendingActionRequest, opts ...grpc.CallOption) (*ApprovePendingActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePendingActionResponse)
	err := c.cc.Invoke(ctx, BankaService_ApprovePendingAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) VerifyLimitChange(ctx context.Context, in *VerifyLimitChangeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_VerifyLimitChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetPaymentRecipients(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPaymentRecipientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentRecipientsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetPaymentRecipients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) CreatePaymentRecipient(ctx context.Context, in *CreatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientItem)
	err := c.cc.Invoke(ctx, BankaService_CreatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) UpdatePaymentRecipient(ctx context.Context, in *UpdatePaymentRecipientRequest, opts ...grpc.CallOption) (*PaymentRecipientItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentRecipientItem)
	err := c.cc.Invoke(ctx, BankaService_UpdatePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) DeletePaymentRecipient(ctx context.Context, in *DeletePaymentRecipientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_DeletePaymentRecipient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, BankaService_CreatePaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) CreateTransferIntent(ctx context.Context, in *CreateTransferIntentRequest, opts ...grpc.CallOption) (*CreatePaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentIntentResponse)
	err := c.cc.Invoke(ctx, BankaService_CreateTransferIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) VerifyAndExecutePayment(ctx context.Context, in *VerifyPaymentRequest, opts ...grpc.CallOption) (*PaymentIntentItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentIntentItem)
	err := c.cc.Invoke(ctx, BankaService_VerifyAndExecutePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentHistoryResponse)
	err := c.cc.Invoke(ctx, BankaService_GetPaymentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetPaymentDetail(ctx context.Context, in *GetPaymentDetailRequest, opts ...grpc.CallOption) (*PaymentIntentItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentIntentItem)
	err := c.cc.Invoke(ctx, BankaService_GetPaymentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) ApplyForCredit(ctx context.Context, in *ApplyForCreditRequest, opts ...grpc.CallOption) (*ApplyForCreditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyForCreditResponse)
	err := c.cc.Invoke(ctx, BankaService_ApplyForCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetClientCredits(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClientCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClientCreditsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetClientCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetCreditDetails(ctx context.Context, in *GetCreditDetailsRequest, opts ...grpc.CallOption) (*GetCreditDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreditDetailsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetCreditDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAllCreditRequests(ctx context.Context, in *GetAllCreditRequestsRequest, opts ...grpc.CallOption) (*GetAllCreditRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCreditRequestsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetAllCreditRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) ApproveCredit(ctx context.Context, in *ApproveCreditRequest, opts ...grpc.CallOption) (*ApproveCreditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCreditResponse)
	err := c.cc.Invoke(ctx, BankaService_ApproveCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) RejectCredit(ctx context.Context, in *RejectCreditRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_RejectCredit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAllApprovedCredits(ctx context.Context, in *GetAllApprovedCreditsRequest, opts ...grpc.CallOption) (*GetAllApprovedCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllApprovedCreditsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetAllApprovedCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) EmployeeChangeCardStatus(ctx context.Context, in *EmployeeChangeCardStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_EmployeeChangeCardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAllAccounts(ctx context.Context, in *GetAllAccountsRequest, opts ...grpc.CallOption) (*GetAllAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllAccountsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetAllAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetAccountCards(ctx context.Context, in *GetAccountCardsRequest, opts ...grpc.CallOption) (*GetAccountCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountCardsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetAccountCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) ListExchanges(ctx context.Context, in *ListExchangesRequest, opts ...grpc.CallOption) (*ListExchangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExchangesResponse)
	err := c.cc.Invoke(ctx, BankaService_ListExchanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetExchange(ctx context.Context, in *GetExchangeRequest, opts ...grpc.CallOption) (*Exchange, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exchange)
	err := c.cc.Invoke(ctx, BankaService_GetExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) ToggleMarketTestMode(ctx context.Context, in *ToggleMarketTestModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, BankaService_ToggleMarketTestMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetListings(ctx context.Context, in *GetListingsRequest, opts ...grpc.CallOption) (*GetListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingsResponse)
	err := c.cc.Invoke(ctx, BankaService_GetListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetListingByID(ctx context.Context, in *GetListingByIDRequest, opts ...grpc.CallOption) (*ListingDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListingDetail)
	err := c.cc.Invoke(ctx, BankaService_GetListingByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) GetListingHistory(ctx context.Context, in *GetListingHistoryRequest, opts ...grpc.CallOption) (*GetListingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingHistoryResponse)
	err := c.cc.Invoke(ctx, BankaService_GetListingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) CreateListingOrder(ctx context.Context, in *CreateListingOrderRequest, opts ...grpc.CallOption) (*CreateListingOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateListingOrderResponse)
	err := c.cc.Invoke(ctx, BankaService_CreateListingOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingCalculate(ctx context.Context, in *TradingCalculateRequest, opts ...grpc.CallOption) (*TradingCalculateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingCalculateResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingCalculate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingCreateOrder(ctx context.Context, in *TradingCreateOrderRequest, opts ...grpc.CallOption) (*TradingCreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingCreateOrderResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingCreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingListOrders(ctx context.Context, in *TradingListOrdersRequest, opts ...grpc.CallOption) (*TradingListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingListOrdersResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingApproveOrder(ctx context.Context, in *TradingApproveOrderRequest, opts ...grpc.CallOption) (*TradingApproveOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingApproveOrderResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingApproveOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingDeclineOrder(ctx context.Context, in *TradingDeclineOrderRequest, opts ...grpc.CallOption) (*TradingDeclineOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingDeclineOrderResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingDeclineOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankaServiceClient) TradingCancelOrder(ctx context.Context, in *TradingCancelOrderRequest, opts ...grpc.CallOption) (*TradingCancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradingCancelOrderResponse)
	err := c.cc.Invoke(ctx, BankaService_TradingCancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankaServiceServer is the server API for BankaService service.
// All implementations must embed UnimplementedBankaServiceServer
// for forward compatibility.
type BankaServiceServer interface {
	// GetCurrencies — javna metoda, vraća sve podržane valute.
	GetCurrencies(context.Context, *emptypb.Empty) (*GetCurrenciesResponse, error)
	// GetDelatnosti — javna metoda, vraća šifarnik delatnosti.
	GetDelatnosti(context.Context, *emptypb.Empty) (*GetDelatnostiResponse, error)
	// CreateAccount — Employee only. Kreira novi bankovni račun.
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// GetClientAccounts — Client only. Vraća aktivne račune trenutno prijavljenog klijenta.
	GetClientAccounts(context.Context, *emptypb.Empty) (*GetClientAccountsResponse, error)
	// GetAccountDetail — Client only. Vraća detalje jednog računa.
	GetAccountDetail(context.Context, *GetAccountDetailRequest) (*AccountDetail, error)
	// GetAccountTransactions — Client only. Vraća transakcije za dati račun.
	GetAccountTransactions(context.Context, *GetAccountTransactionsRequest) (*GetAccountTransactionsResponse, error)
	// RenameAccount — Client only. Menja naziv računa.
	RenameAccount(context.Context, *RenameAccountRequest) (*emptypb.Empty, error)
	// UpdateAccountLimit — Client only. Kreira pending action za promenu limita.
	UpdateAccountLimit(context.Context, *UpdateAccountLimitRequest) (*UpdateAccountLimitResponse, error)
	// GetPendingAction — Client only. Vraća jednu pending akciju.
	GetPendingAction(context.Context, *GetPendingActionRequest) (*GetPendingActionResponse, error)
	// GetPendingActions — Client only. Vraća pending akcije za mobilni.
	// MORA biti registrovana POSLE GetPendingAction jer grpc-gateway v2 prepend-uje handlere
	// (poslje registrovani imaju prioritet). Statička ruta /pending mora pobediti {id}.
	GetPendingActions(context.Context, *emptypb.Empty) (*GetPendingActionsResponse, error)
	// ApprovePendingAction — Client only. Odobrava akciju i generiše verifikacioni kod.
	ApprovePendingAction(context.Context, *ApprovePendingActionRequest) (*ApprovePendingActionResponse, error)
	// VerifyLimitChange — Client only. Proverava kod i primenjuje promenu limita.
	VerifyLimitChange(context.Context, *VerifyLimitChangeRequest) (*emptypb.Empty, error)
	// GetPaymentRecipients — Client only. Lista sačuvanih primalaca.
	GetPaymentRecipients(context.Context, *emptypb.Empty) (*GetPaymentRecipientsResponse, error)
	// CreatePaymentRecipient — Client only. Dodaje novog primaoca.
	CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientItem, error)
	// UpdatePaymentRecipient — Client only. Menja primaoca.
	UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientItem, error)
	// DeletePaymentRecipient — Client only. Briše primaoca.
	DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*emptypb.Empty, error)
	// CreatePaymentIntent — Client only. Kreira nalog plaćanja i pokreće verifikaciju.
	CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error)
	// CreateTransferIntent — Client only. Kreira nalog prenosa između računa istog klijenta.
	CreateTransferIntent(context.Context, *CreateTransferIntentRequest) (*CreatePaymentIntentResponse, error)
	// VerifyAndExecutePayment — Client only. Proverava verifikacioni kod i izvršava plaćanje.
	VerifyAndExecutePayment(context.Context, *VerifyPaymentRequest) (*PaymentIntentItem, error)
	// GetPaymentHistory — Client only. Istorija plaćanja sa filterima.
	GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error)
	// GetPaymentDetail — Client only. Detalji jednog naloga.
	GetPaymentDetail(context.Context, *GetPaymentDetailRequest) (*PaymentIntentItem, error)
	// ApplyForCredit — Client only. Podnosi zahtev za novi kredit.
	ApplyForCredit(context.Context, *ApplyForCreditRequest) (*ApplyForCreditResponse, error)
	// GetClientCredits — Client only. Vraća sve kredite prijavljenog klijenta, sortirano opadajuće po iznosu.
	GetClientCredits(context.Context, *emptypb.Empty) (*GetClientCreditsResponse, error)
	// GetCreditDetails — Client only. Vraća detalje i rate za jedan kredit.
	GetCreditDetails(context.Context, *GetCreditDetailsRequest) (*GetCreditDetailsResponse, error)
	// GetAllCreditRequests — Employee only. Vraća sve zahteve za kredit sa opcionim filterima.
	GetAllCreditRequests(context.Context, *GetAllCreditRequestsRequest) (*GetAllCreditRequestsResponse, error)
	// ApproveCredit — Employee only. Odobrava zahtev za kredit i uplaćuje iznos na račun klijenta.
	ApproveCredit(context.Context, *ApproveCreditRequest) (*ApproveCreditResponse, error)
	// RejectCredit — Employee only. Odbija zahtev za kredit.
	RejectCredit(context.Context, *RejectCreditRequest) (*emptypb.Empty, error)
	// GetAllApprovedCredits — Employee only. Vraća sve odobrene kredite sa opcionim filterima, sortirano po broju računa.
	GetAllApprovedCredits(context.Context, *GetAllApprovedCreditsRequest) (*GetAllApprovedCreditsResponse, error)
	// EmployeeChangeCardStatus — Employee only. Menja status kartice (blokada/deblokada/deaktivacija).
	// Nakon uspešne promene šalje asinhronu email notifikaciju vlasniku, a za poslovne račune
	// i ovlašćenom licu (email se čita iz lokalne baze, bez dodatnog poziva ka user-service-u).
	EmployeeChangeCardStatus(context.Context, *EmployeeChangeCardStatusRequest) (*emptypb.Empty, error)
	// GetAllAccounts — Employee only. Vraća agregiranu listu svih računa klijenata,
	// sortiranu abecedno po prezimenu vlasnika. Podržava filtere po broju računa,
	// imenu i prezimenu vlasnika (prosleđuju se kao query parametri).
	GetAllAccounts(context.Context, *GetAllAccountsRequest) (*GetAllAccountsResponse, error)
	// GetAccountCards — Employee only. Vraća sve kartice vezane za dati račun.
	// Ime, prezime i email vlasnika dohvataju se sinhronim pozivom ka user-service-u.
	GetAccountCards(context.Context, *GetAccountCardsRequest) (*GetAccountCardsResponse, error)
	// ListExchanges — javna metoda. Vraća listu berzi sa opcionim filterima.
	// Filteri: polity (tačno poklapanje), search (parcijalni match na name/acronym).
	ListExchanges(context.Context, *ListExchangesRequest) (*ListExchangesResponse, error)
	// GetExchange — javna metoda. Dohvata jednu berzu po ID-u ili MIC kodu.
	// Prosleđuje se ili id (path param) ili mic_code (query param) — ne oba.
	GetExchange(context.Context, *GetExchangeRequest) (*Exchange, error)
	// ToggleMarketTestMode — Admin/Employee only. Uključuje ili isključuje
	// bypass radnog vremena berzi (čuva se u Redisu pod ključem market:test_mode).
	ToggleMarketTestMode(context.Context, *ToggleMarketTestModeRequest) (*emptypb.Empty, error)
	// GetListings — Client only. Vraća listu hartija sa filterima i paginacijom.
	GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error)
	// GetListingByID — Client only. Vraća detalje jedne hartije po ID-u.
	GetListingByID(context.Context, *GetListingByIDRequest) (*ListingDetail, error)
	// GetListingHistory — Client only. Vraća istoriju dnevnih cena za datu hartiju.
	GetListingHistory(context.Context, *GetListingHistoryRequest) (*GetListingHistoryResponse, error)
	// CreateListingOrder — Client only. Provera raspoloživog stanja; ne knjiži trgovinu (Celina 4).
	CreateListingOrder(context.Context, *CreateListingOrderRequest) (*CreateListingOrderResponse, error)
	// TradingCalculate — Authenticated. Vraća procenu cene i provizije bez perzistencije.
	TradingCalculate(context.Context, *TradingCalculateRequest) (*TradingCalculateResponse, error)
	// TradingCreateOrder — Authenticated. Kreira novi nalog; workflow odobravanja je u servisu.
	TradingCreateOrder(context.Context, *TradingCreateOrderRequest) (*TradingCreateOrderResponse, error)
	// TradingListOrders — Employee only. Lista naloga sa opcionim filterom statusa.
	TradingListOrders(context.Context, *TradingListOrdersRequest) (*TradingListOrdersResponse, error)
	// TradingApproveOrder — Employee only. Odobrava PENDING nalog.
	TradingApproveOrder(context.Context, *TradingApproveOrderRequest) (*TradingApproveOrderResponse, error)
	// TradingDeclineOrder — Employee only. Odbija PENDING nalog.
	TradingDeclineOrder(context.Context, *TradingDeclineOrderRequest) (*TradingDeclineOrderResponse, error)
	// TradingCancelOrder — Vlasnik naloga ili Employee. Otkazuje aktivan nalog.
	TradingCancelOrder(context.Context, *TradingCancelOrderRequest) (*TradingCancelOrderResponse, error)
	mustEmbedUnimplementedBankaServiceServer()
}

// UnimplementedBankaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankaServiceServer struct{}

func (UnimplementedBankaServiceServer) GetCurrencies(context.Context, *emptypb.Empty) (*GetCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (UnimplementedBankaServiceServer) GetDelatnosti(context.Context, *emptypb.Empty) (*GetDelatnostiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDelatnosti not implemented")
}
func (UnimplementedBankaServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedBankaServiceServer) GetClientAccounts(context.Context, *emptypb.Empty) (*GetClientAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientAccounts not implemented")
}
func (UnimplementedBankaServiceServer) GetAccountDetail(context.Context, *GetAccountDetailRequest) (*AccountDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountDetail not implemented")
}
func (UnimplementedBankaServiceServer) GetAccountTransactions(context.Context, *GetAccountTransactionsRequest) (*GetAccountTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountTransactions not implemented")
}
func (UnimplementedBankaServiceServer) RenameAccount(context.Context, *RenameAccountRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameAccount not implemented")
}
func (UnimplementedBankaServiceServer) UpdateAccountLimit(context.Context, *UpdateAccountLimitRequest) (*UpdateAccountLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAccountLimit not implemented")
}
func (UnimplementedBankaServiceServer) GetPendingAction(context.Context, *GetPendingActionRequest) (*GetPendingActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingAction not implemented")
}
func (UnimplementedBankaServiceServer) GetPendingActions(context.Context, *emptypb.Empty) (*GetPendingActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingActions not implemented")
}
func (UnimplementedBankaServiceServer) ApprovePendingAction(context.Context, *ApprovePendingActionRequest) (*ApprovePendingActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePendingAction not implemented")
}
func (UnimplementedBankaServiceServer) VerifyLimitChange(context.Context, *VerifyLimitChangeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyLimitChange not implemented")
}
func (UnimplementedBankaServiceServer) GetPaymentRecipients(context.Context, *emptypb.Empty) (*GetPaymentRecipientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentRecipients not implemented")
}
func (UnimplementedBankaServiceServer) CreatePaymentRecipient(context.Context, *CreatePaymentRecipientRequest) (*PaymentRecipientItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentRecipient not implemented")
}
func (UnimplementedBankaServiceServer) UpdatePaymentRecipient(context.Context, *UpdatePaymentRecipientRequest) (*PaymentRecipientItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePaymentRecipient not implemented")
}
func (UnimplementedBankaServiceServer) DeletePaymentRecipient(context.Context, *DeletePaymentRecipientRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePaymentRecipient not implemented")
}
func (UnimplementedBankaServiceServer) CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentIntent not implemented")
}
func (UnimplementedBankaServiceServer) CreateTransferIntent(context.Context, *CreateTransferIntentRequest) (*CreatePaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTransferIntent not implemented")
}
func (UnimplementedBankaServiceServer) VerifyAndExecutePayment(context.Context, *VerifyPaymentRequest) (*PaymentIntentItem, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyAndExecutePayment not implemented")
}
func (UnimplementedBankaServiceServer) GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentHistory not implemented")
}
func (UnimplementedBankaServiceServer) GetPaymentDetail(context.Context, *GetPaymentDetailRequest) (*PaymentIntentItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentDetail not implemented")
}
func (UnimplementedBankaServiceServer) ApplyForCredit(context.Context, *ApplyForCreditRequest) (*ApplyForCreditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyForCredit not implemented")
}
func (UnimplementedBankaServiceServer) GetClientCredits(context.Context, *emptypb.Empty) (*GetClientCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClientCredits not implemented")
}
func (UnimplementedBankaServiceServer) GetCreditDetails(context.Context, *GetCreditDetailsRequest) (*GetCreditDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreditDetails not implemented")
}
func (UnimplementedBankaServiceServer) GetAllCreditRequests(context.Context, *GetAllCreditRequestsRequest) (*GetAllCreditRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllCreditRequests not implemented")
}
func (UnimplementedBankaServiceServer) ApproveCredit(context.Context, *ApproveCreditRequest) (*ApproveCreditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveCredit not implemented")
}
func (UnimplementedBankaServiceServer) RejectCredit(context.Context, *RejectCreditRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectCredit not implemented")
}
func (UnimplementedBankaServiceServer) GetAllApprovedCredits(context.Context, *GetAllApprovedCreditsRequest) (*GetAllApprovedCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllApprovedCredits not implemented")
}
func (UnimplementedBankaServiceServer) EmployeeChangeCardStatus(context.Context, *EmployeeChangeCardStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EmployeeChangeCardStatus not implemented")
}
func (UnimplementedBankaServiceServer) GetAllAccounts(context.Context, *GetAllAccountsRequest) (*GetAllAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllAccounts not implemented")
}
func (UnimplementedBankaServiceServer) GetAccountCards(context.Context, *GetAccountCardsRequest) (*GetAccountCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountCards not implemented")
}
func (UnimplementedBankaServiceServer) ListExchanges(context.Context, *ListExchangesRequest) (*ListExchangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExchanges not implemented")
}
func (UnimplementedBankaServiceServer) GetExchange(context.Context, *GetExchangeRequest) (*Exchange, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExchange not implemented")
}
func (UnimplementedBankaServiceServer) ToggleMarketTestMode(context.Context, *ToggleMarketTestModeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleMarketTestMode not implemented")
}
func (UnimplementedBankaServiceServer) GetListings(context.Context, *GetListingsRequest) (*GetListingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListings not implemented")
}
func (UnimplementedBankaServiceServer) GetListingByID(context.Context, *GetListingByIDRequest) (*ListingDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListingByID not implemented")
}
func (UnimplementedBankaServiceServer) GetListingHistory(context.Context, *GetListingHistoryRequest) (*GetListingHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListingHistory not implemented")
}
func (UnimplementedBankaServiceServer) CreateListingOrder(context.Context, *CreateListingOrderRequest) (*CreateListingOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListingOrder not implemented")
}
func (UnimplementedBankaServiceServer) TradingCalculate(context.Context, *TradingCalculateRequest) (*TradingCalculateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingCalculate not implemented")
}
func (UnimplementedBankaServiceServer) TradingCreateOrder(context.Context, *TradingCreateOrderRequest) (*TradingCreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingCreateOrder not implemented")
}
func (UnimplementedBankaServiceServer) TradingListOrders(context.Context, *TradingListOrdersRequest) (*TradingListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingListOrders not implemented")
}
func (UnimplementedBankaServiceServer) TradingApproveOrder(context.Context, *TradingApproveOrderRequest) (*TradingApproveOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingApproveOrder not implemented")
}
func (UnimplementedBankaServiceServer) TradingDeclineOrder(context.Context, *TradingDeclineOrderRequest) (*TradingDeclineOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingDeclineOrder not implemented")
}
func (UnimplementedBankaServiceServer) TradingCancelOrder(context.Context, *TradingCancelOrderRequest) (*TradingCancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TradingCancelOrder not implemented")
}
func (UnimplementedBankaServiceServer) mustEmbedUnimplementedBankaServiceServer() {}
func (UnimplementedBankaServiceServer) testEmbeddedByValue()                      {}

// UnsafeBankaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankaServiceServer will
// result in compilation errors.
type UnsafeBankaServiceServer interface {
	mustEmbedUnimplementedBankaServiceServer()
}

func RegisterBankaServiceServer(s grpc.ServiceRegistrar, srv BankaServiceServer) {
	// If the following call panics, it indicates UnimplementedBankaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankaService_ServiceDesc, srv)
}

func _BankaService_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetCurrencies(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetDelatnosti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetDelatnosti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetDelatnosti_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetDelatnosti(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetClientAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetClientAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetClientAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetClientAccounts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAccountDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAccountDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAccountDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAccountDetail(ctx, req.(*GetAccountDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAccountTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAccountTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAccountTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAccountTransactions(ctx, req.(*GetAccountTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_RenameAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).RenameAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_RenameAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).RenameAccount(ctx, req.(*RenameAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_UpdateAccountLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).UpdateAccountLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_UpdateAccountLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).UpdateAccountLimit(ctx, req.(*UpdateAccountLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetPendingAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetPendingAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetPendingAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetPendingAction(ctx, req.(*GetPendingActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetPendingActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetPendingActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetPendingActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetPendingActions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_ApprovePendingAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePendingActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).ApprovePendingAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_ApprovePendingAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).ApprovePendingAction(ctx, req.(*ApprovePendingActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_VerifyLimitChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyLimitChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).VerifyLimitChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_VerifyLimitChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).VerifyLimitChange(ctx, req.(*VerifyLimitChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetPaymentRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetPaymentRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetPaymentRecipients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetPaymentRecipients(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_CreatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).CreatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_CreatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).CreatePaymentRecipient(ctx, req.(*CreatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_UpdatePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).UpdatePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_UpdatePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).UpdatePaymentRecipient(ctx, req.(*UpdatePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_DeletePaymentRecipient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePaymentRecipientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).DeletePaymentRecipient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_DeletePaymentRecipient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).DeletePaymentRecipient(ctx, req.(*DeletePaymentRecipientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_CreatePaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).CreatePaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_CreatePaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).CreatePaymentIntent(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_CreateTransferIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransferIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).CreateTransferIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_CreateTransferIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).CreateTransferIntent(ctx, req.(*CreateTransferIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_VerifyAndExecutePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).VerifyAndExecutePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_VerifyAndExecutePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).VerifyAndExecutePayment(ctx, req.(*VerifyPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetPaymentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetPaymentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetPaymentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetPaymentHistory(ctx, req.(*GetPaymentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetPaymentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetPaymentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetPaymentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetPaymentDetail(ctx, req.(*GetPaymentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_ApplyForCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyForCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).ApplyForCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_ApplyForCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).ApplyForCredit(ctx, req.(*ApplyForCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetClientCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetClientCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetClientCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetClientCredits(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetCreditDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetCreditDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetCreditDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetCreditDetails(ctx, req.(*GetCreditDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAllCreditRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCreditRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAllCreditRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAllCreditRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAllCreditRequests(ctx, req.(*GetAllCreditRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_ApproveCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).ApproveCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_ApproveCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).ApproveCredit(ctx, req.(*ApproveCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_RejectCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).RejectCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_RejectCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).RejectCredit(ctx, req.(*RejectCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAllApprovedCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllApprovedCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAllApprovedCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAllApprovedCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAllApprovedCredits(ctx, req.(*GetAllApprovedCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_EmployeeChangeCardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeChangeCardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).EmployeeChangeCardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_EmployeeChangeCardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).EmployeeChangeCardStatus(ctx, req.(*EmployeeChangeCardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAllAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAllAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAllAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAllAccounts(ctx, req.(*GetAllAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetAccountCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetAccountCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetAccountCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetAccountCards(ctx, req.(*GetAccountCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_ListExchanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExchangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).ListExchanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_ListExchanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).ListExchanges(ctx, req.(*ListExchangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetExchange(ctx, req.(*GetExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_ToggleMarketTestMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleMarketTestModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).ToggleMarketTestMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_ToggleMarketTestMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).ToggleMarketTestMode(ctx, req.(*ToggleMarketTestModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetListings(ctx, req.(*GetListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetListingByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetListingByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetListingByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetListingByID(ctx, req.(*GetListingByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_GetListingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).GetListingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_GetListingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).GetListingHistory(ctx, req.(*GetListingHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_CreateListingOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListingOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).CreateListingOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_CreateListingOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).CreateListingOrder(ctx, req.(*CreateListingOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingCalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingCalculate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingCalculate(ctx, req.(*TradingCalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingCreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingCreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingCreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingCreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingCreateOrder(ctx, req.(*TradingCreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingListOrders(ctx, req.(*TradingListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingApproveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingApproveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingApproveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingApproveOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingApproveOrder(ctx, req.(*TradingApproveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingDeclineOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingDeclineOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingDeclineOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingDeclineOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingDeclineOrder(ctx, req.(*TradingDeclineOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankaService_TradingCancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradingCancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankaServiceServer).TradingCancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankaService_TradingCancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankaServiceServer).TradingCancelOrder(ctx, req.(*TradingCancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BankaService_ServiceDesc is the grpc.ServiceDesc for BankaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banka.v1.BankaService",
	HandlerType: (*BankaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencies",
			Handler:    _BankaService_GetCurrencies_Handler,
		},
		{
			MethodName: "GetDelatnosti",
			Handler:    _BankaService_GetDelatnosti_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _BankaService_CreateAccount_Handler,
		},
		{
			MethodName: "GetClientAccounts",
			Handler:    _BankaService_GetClientAccounts_Handler,
		},
		{
			MethodName: "GetAccountDetail",
			Handler:    _BankaService_GetAccountDetail_Handler,
		},
		{
			MethodName: "GetAccountTransactions",
			Handler:    _BankaService_GetAccountTransactions_Handler,
		},
		{
			MethodName: "RenameAccount",
			Handler:    _BankaService_RenameAccount_Handler,
		},
		{
			MethodName: "UpdateAccountLimit",
			Handler:    _BankaService_UpdateAccountLimit_Handler,
		},
		{
			MethodName: "GetPendingAction",
			Handler:    _BankaService_GetPendingAction_Handler,
		},
		{
			MethodName: "GetPendingActions",
			Handler:    _BankaService_GetPendingActions_Handler,
		},
		{
			MethodName: "ApprovePendingAction",
			Handler:    _BankaService_ApprovePendingAction_Handler,
		},
		{
			MethodName: "VerifyLimitChange",
			Handler:    _BankaService_VerifyLimitChange_Handler,
		},
		{
			MethodName: "GetPaymentRecipients",
			Handler:    _BankaService_GetPaymentRecipients_Handler,
		},
		{
			MethodName: "CreatePaymentRecipient",
			Handler:    _BankaService_CreatePaymentRecipient_Handler,
		},
		{
			MethodName: "UpdatePaymentRecipient",
			Handler:    _BankaService_UpdatePaymentRecipient_Handler,
		},
		{
			MethodName: "DeletePaymentRecipient",
			Handler:    _BankaService_DeletePaymentRecipient_Handler,
		},
		{
			MethodName: "CreatePaymentIntent",
			Handler:    _BankaService_CreatePaymentIntent_Handler,
		},
		{
			MethodName: "CreateTransferIntent",
			Handler:    _BankaService_CreateTransferIntent_Handler,
		},
		{
			MethodName: "VerifyAndExecutePayment",
			Handler:    _BankaService_VerifyAndExecutePayment_Handler,
		},
		{
			MethodName: "GetPaymentHistory",
			Handler:    _BankaService_GetPaymentHistory_Handler,
		},
		{
			MethodName: "GetPaymentDetail",
			Handler:    _BankaService_GetPaymentDetail_Handler,
		},
		{
			MethodName: "ApplyForCredit",
			Handler:    _BankaService_ApplyForCredit_Handler,
		},
		{
			MethodName: "GetClientCredits",
			Handler:    _BankaService_GetClientCredits_Handler,
		},
		{
			MethodName: "GetCreditDetails",
			Handler:    _BankaService_GetCreditDetails_Handler,
		},
		{
			MethodName: "GetAllCreditRequests",
			Handler:    _BankaService_GetAllCreditRequests_Handler,
		},
		{
			MethodName: "ApproveCredit",
			Handler:    _BankaService_ApproveCredit_Handler,
		},
		{
			MethodName: "RejectCredit",
			Handler:    _BankaService_RejectCredit_Handler,
		},
		{
			MethodName: "GetAllApprovedCredits",
			Handler:    _BankaService_GetAllApprovedCredits_Handler,
		},
		{
			MethodName: "EmployeeChangeCardStatus",
			Handler:    _BankaService_EmployeeChangeCardStatus_Handler,
		},
		{
			MethodName: "GetAllAccounts",
			Handler:    _BankaService_GetAllAccounts_Handler,
		},
		{
			MethodName: "GetAccountCards",
			Handler:    _BankaService_GetAccountCards_Handler,
		},
		{
			MethodName: "ListExchanges",
			Handler:    _BankaService_ListExchanges_Handler,
		},
		{
			MethodName: "GetExchange",
			Handler:    _BankaService_GetExchange_Handler,
		},
		{
			MethodName: "ToggleMarketTestMode",
			Handler:    _BankaService_ToggleMarketTestMode_Handler,
		},
		{
			MethodName: "GetListings",
			Handler:    _BankaService_GetListings_Handler,
		},
		{
			MethodName: "GetListingByID",
			Handler:    _BankaService_GetListingByID_Handler,
		},
		{
			MethodName: "GetListingHistory",
			Handler:    _BankaService_GetListingHistory_Handler,
		},
		{
			MethodName: "CreateListingOrder",
			Handler:    _BankaService_CreateListingOrder_Handler,
		},
		{
			MethodName: "TradingCalculate",
			Handler:    _BankaService_TradingCalculate_Handler,
		},
		{
			MethodName: "TradingCreateOrder",
			Handler:    _BankaService_TradingCreateOrder_Handler,
		},
		{
			MethodName: "TradingListOrders",
			Handler:    _BankaService_TradingListOrders_Handler,
		},
		{
			MethodName: "TradingApproveOrder",
			Handler:    _BankaService_TradingApproveOrder_Handler,
		},
		{
			MethodName: "TradingDeclineOrder",
			Handler:    _BankaService_TradingDeclineOrder_Handler,
		},
		{
			MethodName: "TradingCancelOrder",
			Handler:    _BankaService_TradingCancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/banka/banka.proto",
}
