// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/banka/banka.proto

package bankav1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Currency predstavlja podržanu valutu u sistemu.
type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Naziv         string                 `protobuf:"bytes,2,opt,name=naziv,proto3" json:"naziv,omitempty"`   // e.g. "Srpski dinar"
	Oznaka        string                 `protobuf:"bytes,3,opt,name=oznaka,proto3" json:"oznaka,omitempty"` // ISO 4217 kod, e.g. "RSD", "EUR"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_banka_banka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Currency) GetNaziv() string {
	if x != nil {
		return x.Naziv
	}
	return ""
}

func (x *Currency) GetOznaka() string {
	if x != nil {
		return x.Oznaka
	}
	return ""
}

type GetCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valute        []*Currency            `protobuf:"bytes,1,rep,name=valute,proto3" json:"valute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesResponse) Reset() {
	*x = GetCurrenciesResponse{}
	mi := &file_proto_banka_banka_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesResponse) ProtoMessage() {}

func (x *GetCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrenciesResponse) GetValute() []*Currency {
	if x != nil {
		return x.Valute
	}
	return nil
}

// Delatnost predstavlja šifarnik delatnosti (klasifikacija privrednih subjekata).
type Delatnost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sifra         string                 `protobuf:"bytes,2,opt,name=sifra,proto3" json:"sifra,omitempty"` // šifra delatnosti, e.g. "6411"
	Naziv         string                 `protobuf:"bytes,3,opt,name=naziv,proto3" json:"naziv,omitempty"`
	Grana         string                 `protobuf:"bytes,4,opt,name=grana,proto3" json:"grana,omitempty"`
	Sektor        string                 `protobuf:"bytes,5,opt,name=sektor,proto3" json:"sektor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delatnost) Reset() {
	*x = Delatnost{}
	mi := &file_proto_banka_banka_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delatnost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delatnost) ProtoMessage() {}

func (x *Delatnost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delatnost.ProtoReflect.Descriptor instead.
func (*Delatnost) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{2}
}

func (x *Delatnost) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Delatnost) GetSifra() string {
	if x != nil {
		return x.Sifra
	}
	return ""
}

func (x *Delatnost) GetNaziv() string {
	if x != nil {
		return x.Naziv
	}
	return ""
}

func (x *Delatnost) GetGrana() string {
	if x != nil {
		return x.Grana
	}
	return ""
}

func (x *Delatnost) GetSektor() string {
	if x != nil {
		return x.Sektor
	}
	return ""
}

type GetDelatnostiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delatnosti    []*Delatnost           `protobuf:"bytes,1,rep,name=delatnosti,proto3" json:"delatnosti,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDelatnostiResponse) Reset() {
	*x = GetDelatnostiResponse{}
	mi := &file_proto_banka_banka_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDelatnostiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDelatnostiResponse) ProtoMessage() {}

func (x *GetDelatnostiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDelatnostiResponse.ProtoReflect.Descriptor instead.
func (*GetDelatnostiResponse) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{3}
}

func (x *GetDelatnostiResponse) GetDelatnosti() []*Delatnost {
	if x != nil {
		return x.Delatnosti
	}
	return nil
}

// Firma se popunjava samo za poslovne račune; za fizička lica ostaje null.
type Firma struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Naziv         string                 `protobuf:"bytes,1,opt,name=naziv,proto3" json:"naziv,omitempty"`
	MaticniBroj   string                 `protobuf:"bytes,2,opt,name=maticni_broj,json=maticniBroj,proto3" json:"maticni_broj,omitempty"`
	Pib           string                 `protobuf:"bytes,3,opt,name=pib,proto3" json:"pib,omitempty"`
	DelatnostId   int64                  `protobuf:"varint,4,opt,name=delatnost_id,json=delatnostId,proto3" json:"delatnost_id,omitempty"`
	Adresa        string                 `protobuf:"bytes,5,opt,name=adresa,proto3" json:"adresa,omitempty"`
	VlasnikId     int64                  `protobuf:"varint,6,opt,name=vlasnik_id,json=vlasnikId,proto3" json:"vlasnik_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Firma) Reset() {
	*x = Firma{}
	mi := &file_proto_banka_banka_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Firma) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Firma) ProtoMessage() {}

func (x *Firma) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Firma.ProtoReflect.Descriptor instead.
func (*Firma) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{4}
}

func (x *Firma) GetNaziv() string {
	if x != nil {
		return x.Naziv
	}
	return ""
}

func (x *Firma) GetMaticniBroj() string {
	if x != nil {
		return x.MaticniBroj
	}
	return ""
}

func (x *Firma) GetPib() string {
	if x != nil {
		return x.Pib
	}
	return ""
}

func (x *Firma) GetDelatnostId() int64 {
	if x != nil {
		return x.DelatnostId
	}
	return 0
}

func (x *Firma) GetAdresa() string {
	if x != nil {
		return x.Adresa
	}
	return ""
}

func (x *Firma) GetVlasnikId() int64 {
	if x != nil {
		return x.VlasnikId
	}
	return 0
}

type CreateAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ZaposleniId      int64                  `protobuf:"varint,1,opt,name=zaposleni_id,json=zaposleniId,proto3" json:"zaposleni_id,omitempty"` // ID zaposlenog koji kreira račun
	VlasnikId        int64                  `protobuf:"varint,2,opt,name=vlasnik_id,json=vlasnikId,proto3" json:"vlasnik_id,omitempty"`       // ID vlasnika računa (klijent)
	ValutaId         int64                  `protobuf:"varint,3,opt,name=valuta_id,json=valutaId,proto3" json:"valuta_id,omitempty"`
	Firma            *Firma                 `protobuf:"bytes,4,opt,name=firma,proto3,oneof" json:"firma,omitempty"` // null za fizička lica
	KategorijaRacuna string                 `protobuf:"bytes,5,opt,name=kategorija_racuna,json=kategorijaRacuna,proto3" json:"kategorija_racuna,omitempty"`
	VrstaRacuna      string                 `protobuf:"bytes,6,opt,name=vrsta_racuna,json=vrstaRacuna,proto3" json:"vrsta_racuna,omitempty"`
	Podvrsta         string                 `protobuf:"bytes,7,opt,name=podvrsta,proto3" json:"podvrsta,omitempty"`
	Naziv            string                 `protobuf:"bytes,8,opt,name=naziv,proto3" json:"naziv,omitempty"`
	Stanje           float64                `protobuf:"fixed64,9,opt,name=stanje,proto3" json:"stanje,omitempty"` // početno stanje računa
	KreirajKarticu   bool                   `protobuf:"varint,10,opt,name=kreiraj_karticu,json=kreirajKarticu,proto3" json:"kreiraj_karticu,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_banka_banka_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountRequest) GetZaposleniId() int64 {
	if x != nil {
		return x.ZaposleniId
	}
	return 0
}

func (x *CreateAccountRequest) GetVlasnikId() int64 {
	if x != nil {
		return x.VlasnikId
	}
	return 0
}

func (x *CreateAccountRequest) GetValutaId() int64 {
	if x != nil {
		return x.ValutaId
	}
	return 0
}

func (x *CreateAccountRequest) GetFirma() *Firma {
	if x != nil {
		return x.Firma
	}
	return nil
}

func (x *CreateAccountRequest) GetKategorijaRacuna() string {
	if x != nil {
		return x.KategorijaRacuna
	}
	return ""
}

func (x *CreateAccountRequest) GetVrstaRacuna() string {
	if x != nil {
		return x.VrstaRacuna
	}
	return ""
}

func (x *CreateAccountRequest) GetPodvrsta() string {
	if x != nil {
		return x.Podvrsta
	}
	return ""
}

func (x *CreateAccountRequest) GetNaziv() string {
	if x != nil {
		return x.Naziv
	}
	return ""
}

func (x *CreateAccountRequest) GetStanje() float64 {
	if x != nil {
		return x.Stanje
	}
	return 0
}

func (x *CreateAccountRequest) GetKreirajKarticu() bool {
	if x != nil {
		return x.KreirajKarticu
	}
	return false
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID novokreiranog računa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_banka_banka_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_banka_banka_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_banka_banka_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_banka_banka_proto protoreflect.FileDescriptor

const file_proto_banka_banka_proto_rawDesc = "" +
	"\n" +
	"\x17proto/banka/banka.proto\x12\bbanka.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05naziv\x18\x02 \x01(\tR\x05naziv\x12\x16\n" +
	"\x06oznaka\x18\x03 \x01(\tR\x06oznaka\"C\n" +
	"\x15GetCurrenciesResponse\x12*\n" +
	"\x06valute\x18\x01 \x03(\v2\x12.banka.v1.CurrencyR\x06valute\"u\n" +
	"\tDelatnost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05sifra\x18\x02 \x01(\tR\x05sifra\x12\x14\n" +
	"\x05naziv\x18\x03 \x01(\tR\x05naziv\x12\x14\n" +
	"\x05grana\x18\x04 \x01(\tR\x05grana\x12\x16\n" +
	"\x06sektor\x18\x05 \x01(\tR\x06sektor\"L\n" +
	"\x15GetDelatnostiResponse\x123\n" +
	"\n" +
	"delatnosti\x18\x01 \x03(\v2\x13.banka.v1.DelatnostR\n" +
	"delatnosti\"\xac\x01\n" +
	"\x05Firma\x12\x14\n" +
	"\x05naziv\x18\x01 \x01(\tR\x05naziv\x12!\n" +
	"\fmaticni_broj\x18\x02 \x01(\tR\vmaticniBroj\x12\x10\n" +
	"\x03pib\x18\x03 \x01(\tR\x03pib\x12!\n" +
	"\fdelatnost_id\x18\x04 \x01(\x03R\vdelatnostId\x12\x16\n" +
	"\x06adresa\x18\x05 \x01(\tR\x06adresa\x12\x1d\n" +
	"\n" +
	"vlasnik_id\x18\x06 \x01(\x03R\tvlasnikId\"\xee\x02\n" +
	"\x14CreateAccountRequest\x12!\n" +
	"\fzaposleni_id\x18\x01 \x01(\x03R\vzaposleniId\x12\x1d\n" +
	"\n" +
	"vlasnik_id\x18\x02 \x01(\x03R\tvlasnikId\x12\x1b\n" +
	"\tvaluta_id\x18\x03 \x01(\x03R\bvalutaId\x12*\n" +
	"\x05firma\x18\x04 \x01(\v2\x0f.banka.v1.FirmaH\x00R\x05firma\x88\x01\x01\x12+\n" +
	"\x11kategorija_racuna\x18\x05 \x01(\tR\x10kategorijaRacuna\x12!\n" +
	"\fvrsta_racuna\x18\x06 \x01(\tR\vvrstaRacuna\x12\x1a\n" +
	"\bpodvrsta\x18\a \x01(\tR\bpodvrsta\x12\x14\n" +
	"\x05naziv\x18\b \x01(\tR\x05naziv\x12\x16\n" +
	"\x06stanje\x18\t \x01(\x01R\x06stanje\x12'\n" +
	"\x0fkreiraj_karticu\x18\n" +
	" \x01(\bR\x0ekreirajKarticuB\b\n" +
	"\x06_firma\"'\n" +
	"\x15CreateAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xc3\x02\n" +
	"\fBankaService\x12b\n" +
	"\rGetCurrencies\x12\x16.google.protobuf.Empty\x1a\x1f.banka.v1.GetCurrenciesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/bank/currencies\x12b\n" +
	"\rGetDelatnosti\x12\x16.google.protobuf.Empty\x1a\x1f.banka.v1.GetDelatnostiResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/bank/delatnosti\x12k\n" +
	"\rCreateAccount\x12\x1e.banka.v1.CreateAccountRequest\x1a\x1f.banka.v1.CreateAccountResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/bank/accountsB#Z!banka-backend/proto/banka;bankav1b\x06proto3"

var (
	file_proto_banka_banka_proto_rawDescOnce sync.Once
	file_proto_banka_banka_proto_rawDescData []byte
)

func file_proto_banka_banka_proto_rawDescGZIP() []byte {
	file_proto_banka_banka_proto_rawDescOnce.Do(func() {
		file_proto_banka_banka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_banka_banka_proto_rawDesc), len(file_proto_banka_banka_proto_rawDesc)))
	})
	return file_proto_banka_banka_proto_rawDescData
}

var file_proto_banka_banka_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_banka_banka_proto_goTypes = []any{
	(*Currency)(nil),              // 0: banka.v1.Currency
	(*GetCurrenciesResponse)(nil), // 1: banka.v1.GetCurrenciesResponse
	(*Delatnost)(nil),             // 2: banka.v1.Delatnost
	(*GetDelatnostiResponse)(nil), // 3: banka.v1.GetDelatnostiResponse
	(*Firma)(nil),                 // 4: banka.v1.Firma
	(*CreateAccountRequest)(nil),  // 5: banka.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 6: banka.v1.CreateAccountResponse
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_proto_banka_banka_proto_depIdxs = []int32{
	0, // 0: banka.v1.GetCurrenciesResponse.valute:type_name -> banka.v1.Currency
	2, // 1: banka.v1.GetDelatnostiResponse.delatnosti:type_name -> banka.v1.Delatnost
	4, // 2: banka.v1.CreateAccountRequest.firma:type_name -> banka.v1.Firma
	7, // 3: banka.v1.BankaService.GetCurrencies:input_type -> google.protobuf.Empty
	7, // 4: banka.v1.BankaService.GetDelatnosti:input_type -> google.protobuf.Empty
	5, // 5: banka.v1.BankaService.CreateAccount:input_type -> banka.v1.CreateAccountRequest
	1, // 6: banka.v1.BankaService.GetCurrencies:output_type -> banka.v1.GetCurrenciesResponse
	3, // 7: banka.v1.BankaService.GetDelatnosti:output_type -> banka.v1.GetDelatnostiResponse
	6, // 8: banka.v1.BankaService.CreateAccount:output_type -> banka.v1.CreateAccountResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_banka_banka_proto_init() }
func file_proto_banka_banka_proto_init() {
	if File_proto_banka_banka_proto != nil {
		return
	}
	file_proto_banka_banka_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_banka_banka_proto_rawDesc), len(file_proto_banka_banka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_banka_banka_proto_goTypes,
		DependencyIndexes: file_proto_banka_banka_proto_depIdxs,
		MessageInfos:      file_proto_banka_banka_proto_msgTypes,
	}.Build()
	File_proto_banka_banka_proto = out.File
	file_proto_banka_banka_proto_goTypes = nil
	file_proto_banka_banka_proto_depIdxs = nil
}
